### ISSUE TITLE
调试web版时候，不能进行刷新，一刷新就无限重启页面

### ISSUE THREAD

**Issue by qweqwqsqwwew** [tec8297729/flutter_flexible#1]
调试web版时候，不能网页进行刷新，一刷新就无限重启页面

**Comment by tec8297729** [comment]
在SplashPage/components/AdPage.dart文件中 添加取消定时方法，解决无限刷新的情况，但也会多刷新一次
看你是否需要adPage页面功能

`
if (timeCount <= 0) {
      _timer?.cancel(); // 此处
      Navigator.pushNamed(context, RouteName.appHomePage);
      return;
 }
`

后面会对SplashPage进行重构，适应web版本兼容。

**Comment by tec8297729** [comment]
更新修复了一版本v1.7.0，可以尝试拉取最新的master即可！！
