### ISSUE TITLE
请教几个问题

### ISSUE THREAD

**Issue by uiiang** [tec8297729/flutter_flexible#13]
1，没有使用getx做状态管理，是出于哪些技术方面的考量吗？
2，generated_plugin_registrant.dart是做什么用的，通过什么方式生成？
3，有没有办法定制自己的模板？

**Comment by tec8297729** [comment]
* 没有使用getx做状态管理，是出于哪些技术方面的考量吗？

1. 脚手架项目建立比较早，在那时候状态管理偏多，技术迭代破坏性改造是必然的，选择官方出的状态管理，可维护必有保障！
PS：最早期最无法判断哪些状态管理维护更新频率及问题率，官方保障性肯定比其它第三方多一些
2. provider状态功能简单，易理解上手快，目前迭代破坏性API调整暂时没碰到
3. 通用性考虑，有些项目可能就极小，也没必要集成这么重的功能


* generated_plugin_registrant.dart是做什么用的，通过什么方式生成？
这个是之前flutter自动生成的，自动注入插件到内部的原生代码的，稍后我验证后续版本是否有依赖这个，无依赖就清除了！

* 有没有办法定制自己的模板？
目前没办法定制模板功能，不过有考虑这块功能，可以提提对定制模板有哪些诉求（联系方式）
