### ISSUE TITLE
macOS 14 创建项目时提示未找到脚手架模板文件，请先更新模板

### ISSUE THREAD

**Issue by MaidSG** [tec8297729/flutter_flexible#15]
运行环境： macOS 14 m2pro
执行node全局安装后，更新模板时提示未找到脚手架模板文件，请先更新模板：flib updata
，但是实际上控制台的报错是no such file or directory: /**/node_modules/flib-cli/template
这个应该是安装的时候没创建template，需要去目录里创建一个template文件夹

**Comment by tec8297729** [comment]
使用sodo flib updata更新也会报此错误吗？？

**Comment by MaidSG** [comment]
感谢🙏
