### ISSUE TITLE
升级适配flutter新版本

### ISSUE THREAD

**Issue by KyoShio** [tec8297729/flutter_flexible#16]

**Comment by tec8297729** [comment]
已兼容到最新版本3.24.2，下载v2.1.6
如还有问题可以描述一下相关报错信息等

**Comment by KyoShio** [comment]
目前发现一个问题，运行web版flutter run -d chrome --dart-define=INIT_ENV=dev --web-hostname 0.0.0.0 --web-port 5050，无法正常加载，局域网设备通过192.168.xx.xx:5050访问到也是空白页面，如果是直接新建的空项目是正常的
