### ISSUE TITLE
Npm run build 失敗

### ISSUE THREAD

**Issue by kokitang** [tec8297729/flutter_flexible#17]
![image](https://github.com/user-attachments/assets/fd03d0e8-51fe-47ca-bedd-0e9f79dfe590)
在android\local.properties更改minSdkVersion版本号了已經 
flutter.minSdkVersion=19 / flutter.minSdkVersion=33 都試過
其他的例如 targetSdkVersion compileSdkVersion 加了也不行

**Comment by tec8297729** [comment]
已修复，拉一下最新主分支代码（package.json>version2.1.7），在试一下

android\build.gradle主要调整此文件代码，如是老项目，可以根据这个文件进行调整

**Comment by kokitang** [comment]
谢谢你，辛苦了。
还有这个问题该怎么解决呢请问？
Warning: SDK processing. This version only understands SDK XML versions up to 3 but an SDK XML file of version 4 was encountered. This can happen if you use versions of Android Studio and the command-line tools that were released at different times.

**Comment by tec8297729** [comment]
> 谢谢你，辛苦了。 还有这个问题该怎么解决呢请问？ Warning: SDK processing. This version only understands SDK XML versions up to 3 but an SDK XML file of version 4 was encountered. This can happen if you use versions of Android Studio and the command-line tools that were released at different times.
> 
> Note: /Users/<user_directory>/.pub-cache/hosted/pub.dev/ota_update-6.0.0/android/src/main/java/sk/fourq/otaupdate/OtaUpdatePlugin.java uses or overrides a deprecated API. Note: Recompile with -Xlint:deprecation for details.

清一下flutter缓存，在重新下载相关依赖后在试一下！我这暂时没复现这个警告问题，估计是之前缓存的sdk版本，和现在的不匹配，整体不影响匹配，要是去除警告就要清缓存了
