### ISSUE TITLE
app_mian.dart的ColorFiltered会导致flutter web html模式的渐变色渲染LinearGradient出现问题

### ISSUE THREAD

**Issue by KyoShio** [tec8297729/flutter_flexible#18]

**Comment by tec8297729** [comment]
具体是会报什么错误吗？web html模式下并没有复现使用了LinearGradient后有报错相关信息

ColorFiltered主要设置灰度模式，开启后会全局覆盖所有组件颜色，使用场景就是 纪念日，让所有页面一键设灰

**Comment by tec8297729** [comment]
![image](https://github.com/user-attachments/assets/8f9e3439-7954-4abd-9ce2-64ce66e1cf3a)
使用你的代码，并没有复现 渐变色渲染会出现透明，导致黑块出现

**Comment by KyoShio** [comment]
html 模式会出现flutter run -d chrome --web-renderer html --dart-define=INIT_ENV=dev

**Comment by tec8297729** [comment]
flutter web html模式，ColorFiltered和LinearGradient一起使用是有渲染兼容性问题，官方flutter对web端适配兼容还不全

可以尝试以下解决方案：
1：使用--web-renderer canvaskit渲染
2：使用LinearGradient不要使用width: double.infinity设置宽度，如果需要这样设置宽度，那么必须设置一下左或右边距
```dart
Container(
  height: 200,
  width: double.infinity,
  margin: EdgeInsets.only(left: 1.0), // 左或右设置1边距
  decoration: const BoxDecoration(
      shape: BoxShape.rectangle,
      gradient: LinearGradient(
        begin: Alignment.topCenter,
        end: Alignment.bottomCenter,
        colors: [
          Colors.white,
          Colors.grey,
          Colors.red,
        ],
      )),
),
```
