### ISSUE TITLE
使用作者二次封装的dio库，报错

### ISSUE THREAD

**Issue by CNPolaris** [tec8297729/flutter_flexible#19]
![CleanShot 2024-09-24 at 17 04 44@2x](https://github.com/user-attachments/assets/20fcf4a3-e6ae-4371-85ee-b4dbaf4df2d6)
![CleanShot 2024-09-24 at 17 06 07@2x](https://github.com/user-attachments/assets/c84998d3-57c3-4304-aa39-07137c671475)
这是什么情况？ @tec8297729

**Comment by tec8297729** [comment]
网络访问未通~~本地测试是可以正常使用，
1、先检查一下接口是否能正常访问，baseUrl一带上域名前缀
2、虚拟机APP是否可以网络访问
3、如果有开反向代理，这块只能设置IP:端口号

晚点我打详细点的错误打印出来~~

**Comment by tec8297729** [comment]
输出错误日志信息已经更新到主分支
