### ISSUE TITLE
flib updata 命令失败

### ISSUE THREAD

**Issue by dsxksss** [tec8297729/flutter_flexible#21]
![image](https://github.com/user-attachments/assets/8e4d4a33-29c9-432f-be28-bdf71f1fe483)

**Comment by tec8297729** [comment]
切换一下源更新试试，默认源下载失败，切换源命令：flib setGitRemote

**Comment by dsxksss** [comment]
> 切换一下源更新试试，默认源下载失败，切换源命令：flib setGitRemote

好的感谢

**Comment by dsxksss** [comment]
> 切换一下源更新试试，默认源下载失败，切换源命令：flib setGitRemote

尝试了下，好像依旧报这个错误
![image](https://github.com/user-attachments/assets/a966225b-f790-42d3-8ae4-db06e70f0e04)

**Comment by tec8297729** [comment]
留个联系方式，看一下你本地情况！！因为我这本地没复现这种场景出来

**Comment by dsxksss** [comment]
> 留个联系方式，看一下你本地情况！！因为我这本地没复现这种场景出来

好的，我邮件发给您

**Comment by tec8297729** [comment]
终端powershell兼容性问题，已更新flib-cli做了处理！！

**Comment by dsxksss** [comment]
> 终端powershell兼容性问题，已更新flib-cli做了处理！！

感谢
