### ISSUE TITLE
直接把项目下载下来，项目中的键盘会挡住输入框

### ISSUE THREAD

**Issue by zilanfeng** [tec8297729/flutter_flexible#4]
把登录页面的验证码放入到页面的底部，点击验证码textfield，键盘会挡住验证码，设置resizeToAvoidBottomInset也没用，这是什么情况？

**Comment by tec8297729** [comment]
在什么样的机型会出现这样的情况？

**Comment by zilanfeng** [comment]
我这边试了iPhone的模拟器，安卓的荣耀手机 都是这样，同样一份代码，我新建一个工程，点击底部的textfield，键盘不会挡住输入框，把这个代码挪到这个工程里面，键盘就挡住输入框了

**Comment by tec8297729** [comment]
键盘遮档问题已经修复，拉取最新master分支在试一下！
