### ISSUE TITLE
不错的脚手架项目

### ISSUE THREAD

**Issue by netsesame2** [tec8297729/flutter_flexible#5]
看了好多类似的，大都填满了各种新技术，像个实验室。
比如很多项目都引入了Redux来管理state，action、reducer、store、middleware、stream……其实只有大型项目，才用得上。
作者这个项目，用很实用的Provider/Consumer，整个框架简洁舒服、注释清晰，把一些繁琐的代码进行了封装。非常不错。
感谢作者的分享。
@tec8297729

**Comment by netsesame2** [comment]
我认真的阅读了源码，收获很多

**Comment by tec8297729** [comment]
> 我认真的阅读了源码，收获很多

有所收获就好。

状态管理没必要引入太多概念，官方的状态管理其实完全能满足，并且可以更小颗粒度去更新组件！另外一个角度就是在未来的大版本更新中，减少大成本的改造~如果是自研第三方store很容易出现语法不兼容问题。

PS：也欢迎提各种建议功能需求！

**Comment by netsesame2** [comment]
最近把项目中的Provider更换成了Riverpod。Provider对context的强依赖，在一些场景中使用很受限。
另外，脚手架中DIO中的反向代理设计很棒，解决了我在模拟器中访问本地域名的头疼问题。

@tec8297729
