### ISSUE TITLE
Target of URI doesn't exist: 'package:flutter_flexible/components/layouts/basic_layout.dart'

### ISSUE THREAD

**Issue by zh1326** [tec8297729/flutter_flexible#6]
似乎缺失了依赖，android studio 报了这么一个错

<img width="987" alt="image" src="https://user-images.githubusercontent.com/2149865/234038193-206b9199-d5ff-4a48-aec4-1a21609027f8.png">
<img width="816" alt="image" src="https://user-images.githubusercontent.com/2149865/234038311-edbcf6ee-8ca3-45a3-8f2d-7ddc13a20966.png">

**Comment by tec8297729** [comment]
已经修复了，可以安装最新版本的flib-cli
