### ISSUE TITLE
好奇为啥_preferenceCache初始化之后，guideKey始终是false，更改AppConfig里的isShowWelcome参数也没有用

### ISSUE THREAD

**Issue by CaptXiong** [tec8297729/flutter_flexible#7]
对这个shared_preferences包不熟，好奇为啥_preferenceCache初始化之后，guideKey始终是false，更改AppConfig里的isShowWelcome参数也没有用。

**Comment by tec8297729** [comment]
1.shared_preferences包是用来数据持久化的（保存在本地）
2.guideKey始终返回false，是因为引导页只有首次执行后，会把状态改成false，后续不会在更改状态！！
![image](https://github.com/tec8297729/flutter_flexible/assets/33629079/875eb402-a4c3-4f54-93c8-9d06d746e7c9)

PS：这块根据业务场景，在相应其它地方调整变更参数即可
