### ISSUE TITLE
webview模块有推荐的吗？

### ISSUE THREAD

**Issue by hanxiaofeng** [tec8297729/flutter_flexible#8]
webview模块有推荐的吗？或者直接集成进去

**Comment by tec8297729** [comment]
试试webview_flutter这个，也支持与web交互通信

**Comment by hanxiaofeng** [comment]
@tec8297729 好的，再咨询个问题，如何去除页面切换动画？目前页面跳转是默认的动画效果吗？

**Comment by tec8297729** [comment]
1. 用的是默认跳转动画，如果想除去页面动画效果，需要自定义路由跳转动画类！！继承PageRouteBuilder类自己实现内部逻辑
2. 要是想全局所有页面都用自定义路由跳转动画，就把\lib\routes\generate_route.dart内的MaterialPageRoute方法，替换成自己实现的路由动画类

**Comment by hanxiaofeng** [comment]
> 

感谢回复
