### ISSUE TITLE
updata失败

### ISSUE THREAD

**Issue by littleantfly** [tec8297729/flutter_flexible#9]
安装完成后，执行updata一直卡在91%后就不行了。

<img width="805" alt="image" src="https://github.com/tec8297729/flutter_flexible/assets/7847094/ec9b4b7c-9d91-41fb-a657-02c4cf621c08">

**Comment by tec8297729** [comment]
那是因为终端访问github源不稳定（要fq一下），更新不动！！

目前已经更新了flib-cli一版，重新下载一下此包（默认已指向国内源了）
新增切换源指令：flib setGitRemote
PS：可自由切换回github
